package com.example.ui

object Loc {
    private val en = mapOf(
        "app_name" to "GoVinto",
        "tagline" to "Giving a warm, new beginning to pre-loved treasures",
        "choose_lang" to "Select Your Preferred Language",
        "continue" to "Continue Journey →",
        "login_title" to "Secure Account Sign-Up",
        "login_sub" to "Join GoVinto securely to verify trust and pass on pre-loved treasures with love.",
        "google_signin_btn" to "Continue with Google ▸",
        "google_signin_error" to "Failed to sign up with Google. Please try again.",
        "tab_home" to "Home",
        "tab_sell" to "Sell",
        "tab_messages" to "Messages",
        "tab_profile" to "Profile",
        "search_hint" to "Search pre-loved treasures with a story...",
        "cat_all" to "All",
        "cat_clothes" to "Clothes",
        "cat_electronics" to "Electronics",
        "cat_furniture" to "Furniture",
        "cat_books" to "Books",
        "chat_btn" to "Chat Now 💬",
        "seller_info" to "Seller Partner Info",
        "seller_rating" to "Trust Rating",
        "fresh_beginning" to "New Beginning",
        "price_prefix" to "₹",
        "step_1_title" to "1. Select Item Photo 📸",
        "step_2_title" to "2. Describe & Price 📝",
        "step_3_title" to "3. Publish to New Home 🚀",
        "photo_hint" to "Pick a picture representing your item:",
        "photo_option_clothes" to "👕 Apparel / Clothes",
        "photo_option_elec" to "💻 Laptop / Electronics",
        "photo_option_furn" to "🪑 Desk / Furniture",
        "photo_option_book" to "📚 Novel / Books",
        "title_label" to "What are you passing on? (Title)",
        "desc_label" to "Tell its beautiful story (Description)",
        "price_label" to "Price of item (₹)",
        "cat_select_label" to "Select Category",
        "post_btn" to "Post & Start New Journey ✨",
        "form_error" to "Please fill all details correctly",
        "post_success" to "Added Successfully! May it find a beautiful new beginning! 🎉",
        "my_listings" to "Pre-loved Items Shared",
        "bought_history" to "Treasures Received",
        "sold_history" to "Items Passed On",
        "no_listings" to "No listed treasures yet. Start sharing warmth!",
        "chat_placeholder" to "Type a warm, friendly message...",
        "typing" to "typing...",
        "seller_reply_delay" to "Seller is thinking of a reply...",
        "sign_out" to "Change Language / Sign Out",
        "back_btn" to "Back",
        "sold_tag" to "Passed On ❤️",
        "available_tag" to "Available for a Home"
    )

    private val hi = mapOf(
        "app_name" to "GoVinto",
        "tagline" to "प्यार से इस्तेमाल किए गए उपहारों को दें एक नई शुरुआत",
        "choose_lang" to "अपनी पसंदीदा भाषा चुनें",
        "continue" to "सफर जारी रखें →",
        "login_title" to "सुरक्षित साइन-अप",
        "login_sub" to "भरोसे को सत्यापित करने और प्यार के साथ उपहारों को साझा करने के लिए सुरक्षित रूप से जुड़ें।",
        "google_signin_btn" to "गूगल के साथ आगे बढ़ें ▸",
        "google_signin_error" to "गूगल लॉगिन विफल रहा। कृपया पुनः प्रयास करें।",
        "tab_home" to "होम",
        "tab_sell" to "बेचें",
        "tab_messages" to "संदेश",
        "tab_profile" to "प्रोफ़ाइल",
        "search_hint" to "कहानियों से भरी अनोखी चीज़ें खोजें...",
        "cat_all" to "सभी",
        "cat_clothes" to "कपड़े",
        "cat_electronics" to "इलेक्ट्रॉनिक्स",
        "cat_furniture" to "फर्नीचर",
        "cat_books" to "किताबें",
        "chat_btn" to "अभी चैट करें 💬",
        "seller_info" to "विक्रेता साथी की जानकारी",
        "seller_rating" to "भरोसा रेटिंग",
        "fresh_beginning" to "नई शुरुआत",
        "price_prefix" to "₹",
        "step_1_title" to "1. चीज़ का फोटो चुनें 📸",
        "step_2_title" to "2. मूल्य और विवरण लिखें 📝",
        "step_3_title" to "3. नए घर के लिए पोस्ट करें 🚀",
        "photo_hint" to "अपनी चीज़ का प्रतिनिधित्व करने वाला चित्र चुनें:",
        "photo_option_clothes" to "👕 कपड़े और परिधान",
        "photo_option_elec" to "💻 कंप्यूटर / इलेक्ट्रॉनिक्स",
        "photo_option_furn" to "🪑 स्टडी टेबल / फर्नीचर",
        "photo_option_book" to "📚 पुस्तक संग्रह / किताबें",
        "title_label" to "आप क्या साझा कर रहे हैं? (शीर्षक)",
        "desc_label" to "इसकी प्यारी कहानी बताएं (विवरण)",
        "price_label" to "चीज़ की कीमत (₹)",
        "cat_select_label" to "श्रेणी का चयन करें",
        "post_btn" to "पोस्ट करें और नई यात्रा शुरू करें ✨",
        "form_error" to "कृपया सभी विवरण सही तरीके से भरें",
        "post_success" to "शानदार! सामान सफलतापूर्वक पोस्ट हुआ। इसे जल्द ही नया घर मिले! 🎉",
        "my_listings" to "साझा किया गया सामान",
        "bought_history" to "प्राप्त किए गए उपहार",
        "sold_history" to "दिए गए नए घर",
        "no_listings" to "अभी तक कोई सामान साझा नहीं किया गया है।",
        "chat_placeholder" to "एक दोस्ताना संदेश लिखें...",
        "typing" to "लिख रहा है...",
        "seller_reply_delay" to "विक्रेता उत्तर के बारे में सोच रहा है...",
        "sign_out" to "भाषा बदलें / लॉगआउट",
        "back_btn" to "पीछे",
        "sold_tag" to "नया घर मिला ❤️",
        "available_tag" to "घर की तलाश में"
    )

    fun t(key: String, lang: String): String {
        val targetMap = if (lang.lowercase() == "hi") hi else en
        return targetMap[key] ?: en[key] ?: key
    }
}
